blank_issues_enabled: false
contact_links:
  - name: Support & Questions
    url: https://github.com/eshaanag/CommitIQ---/discussions
    about: Please ask questions or seek support in the Discussions tab.
